```{r}
library(dplyr)
library(randomForest)
```

```{r}
#retain only the numerical variables in personHHData
personHHData <- personHHData %>% 
  select(where(is.numeric))

hh_bgDensity <- hh_bgDensity %>% 
  select(-bg_density)

#combine two data set by hhid
combined_data <- merge(hh_bgDensity, personHHData, by = 'hhid')

nrow(combined_data)
```

```{r}
#Convert bggroup to a factor
combined_data$bggroup <- as.factor(combined_data$bg_group)
```

```{r}
#split data into training and test data set
set.seed(23541)
train_indices <- sample(1:nrow(combined_data), 0.7 * nrow(combined_data))
train_data <- combined_data[train_indices, ]
test_data <- combined_data[-train_indices, ]
```

```{r}
#train the model
rf_model <- randomForest(bggroup ~ . - hhid, data = train_data, ntree = 500, mtry = 3, importance = TRUE)
print(rf_model)
```

```{r}
#Evaluate the Model
predictions <- predict(rf_model, newdata = test_data)

#confusion matrix
confusion_matrix <- table(Predicted = predictions, Actual = test_data$bggroup)
print(confusion_matrix)

# Calculate accuracy
accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)
print(paste("Accuracy:", round(accuracy, 2)))
```

```{r}
# Plot variable importance
varImpPlot(rf_model)

# View importance scores
importance(rf_model)
```